pipeline {
    agent any
    
    stages {
        stage('Git Checkout'){        
            steps{
                git branch: 'main',
                    url: "https://github.com/anmolsaini-hpe/scenario_based_learnings.git"
            }
        }
        
        stage('Deploy with Rollback'){
            steps {
                script{                    
                    sh './1-deploy.sh --rollback-on-failure'
                }
            }
        }
    }
}
